In [1]:
import numpy as np


In [3]:
a = np.array([1,2,3,4,5,6,7,8,9])
print(a)
print(type(a))

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [25]:
a2 = np.zeros(2)
print(a2)
a3 = np.arange(1,13)
print(a3)

[0. 0.]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [12]:
a4 = np.ones((2, 4))
a5 = np.random.randint(1, 100, (4, 4))

In [13]:
print("Array:", a)
print("Random Matrix:\n", a5)

Array: [1 2 3 4 5 6 7 8 9]
Random Matrix:
 [[44 55 73  5]
 [26 70 13 61]
 [84 85 66  5]
 [80 11 34 35]]


In [14]:
#slicing and indexing
print("First element:", a[0])
print("Last 3 elements:", a[-3:])
print("2x2 sub-matrix:\n", a5[:2, :2])


First element: 1
Last 3 elements: [7 8 9]
2x2 sub-matrix:
 [[44 55]
 [26 70]]


In [15]:
#mathematical operations
print("Add:", a + 10)
print("Multiply:", a * 2)
print("Square root:", np.sqrt(a))

Add: [11 12 13 14 15 16 17 18 19]
Multiply: [ 2  4  6  8 10 12 14 16 18]
Square root: [1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.        ]


In [16]:
#axis wise opearations
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Column-wise sum:", matrix.sum(axis=0))
print("Row-wise mean:", matrix.mean(axis=1))

Column-wise sum: [12 15 18]
Row-wise mean: [2. 5. 8.]


In [17]:
#statistical operation
print("Mean:", matrix.mean())
print("Median:", np.median(matrix))
print("Std Dev:", matrix.std())
print("Max:", matrix.max())

Mean: 5.0
Median: 5.0
Std Dev: 2.581988897471611
Max: 9


In [26]:
#reshaping
reshaped = a3.reshape(3, 4)
print("Reshaped:\n", reshaped)

Reshaped:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [27]:
#broadcasting
vector = np.array([10, 20, 30, 40])
broadcasted = reshaped + vector
print("Broadcasting result:\n", broadcasted)

Broadcasting result:
 [[11 22 33 44]
 [15 26 37 48]
 [19 30 41 52]]


In [28]:
#save and load numpy operation
np.save("my_array.npy", reshaped)
loaded_array = np.load("my_array.npy")
print("Loaded array:\n", loaded_array)


Loaded array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [29]:
#numpy and python list comparison
import time
size = 1_000_000

python_list = list(range(size))
numpy_array = np.arange(size)

start = time.time()
python_list = [x * 2 for x in python_list]
print("Python list time:", time.time() - start)

start = time.time()
numpy_array = numpy_array * 2
print("NumPy array time:", time.time() - start)

Python list time: 0.17682290077209473
NumPy array time: 0.005312442779541016
